"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
type Coach = { id: string; full_name: string }; type Slot = { id: string; service_type: string; starts_at: string; ends_at: string; status: string; capacity: number; staff?: { full_name?: string } | null };
const labels: Record<string, string> = { private_training: "تدريب فردي", group_training: "تدريب جماعي", consultation: "استشارة", online_training: "تدريب أونلاين" };
export default function SchedulePage() { const pathname = usePathname(); const onlineOnly = pathname.endsWith("/online") || pathname.includes("online-bookings"); const [coaches,setCoaches]=useState<Coach[]>([]); const [slots,setSlots]=useState<Slot[]>([]); const [message,setMessage]=useState(""); const [role,setRole]=useState("");
  const load=useCallback(async()=>{ const me=await fetch("/api/auth/me"); if(!me.ok){location.href="/login";return;} const profile=await me.json(); setRole(profile.role); const suffix=onlineOnly?"&serviceType=online_training":""; const [coachRes,slotRes]=await Promise.all([fetch("/api/coaches"),fetch(`/api/booking/slots?scope=mine${suffix}`)]); if(coachRes.ok)setCoaches((await coachRes.json()).coaches); if(slotRes.ok)setSlots((await slotRes.json()).slots); else setMessage("تعذر تحميل الجدول."); },[onlineOnly]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/booking/slots",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({coachId:form.get("coachId"),serviceType:onlineOnly?"online_training":form.get("serviceType"),startsAt:form.get("startsAt"),endsAt:form.get("endsAt"),capacity:form.get("capacity"),price:form.get("price"),meetingUrl:form.get("meetingUrl")})});const data=await response.json();setMessage(response.ok?(role==="admin"?"تم اعتماد الموعد ونشره للحجز.":"تم إرسال الوقت للإدارة للموافقة."):data.error||"تعذر الحفظ.");if(response.ok){event.currentTarget.reset();load();}}
  async function review(id:string,status:string){const response=await fetch(`/api/booking/slots/${id}/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const data=await response.json();setMessage(response.ok?"تم تحديث حالة الموعد.":data.error||"تعذر التحديث.");if(response.ok)load();}
  return <main dir="rtl" className="schedule-page"><header><Link href="/portal/admin">بوابة النادي</Link><Link href="/">الموقع العام</Link></header><section><p className="eyebrow">إدارة الأوقات</p><h1>{onlineOnly?"مواعيد التدريب الأونلاين":role==="coach"?"أوقاتك المتاحة":"مواعيد الكوتش"}</h1><p>{onlineOnly?"هذه الخانة مخصصة لجلسات الأونلاين وروابط اللقاء فقط.":"الكوتش يرسل الوقت المقترح؛ ولا يظهر للحجز حتى تعتمد من الإدارة."}</p>{message&&<p className="schedule-message">{message}</p>}<form className="schedule-form" onSubmit={submit}><label>الكوتش<select name="coachId" required>{coaches.map(coach=><option key={coach.id} value={coach.id}>{coach.full_name}</option>)}</select></label>{!onlineOnly&&<label>الخدمة<select name="serviceType"><option value="private_training">تدريب فردي</option><option value="group_training">تدريب جماعي</option><option value="consultation">استشارة</option><option value="online_training">تدريب أونلاين</option></select></label>}<label>يبدأ<input name="startsAt" type="datetime-local" required/></label><label>ينتهي<input name="endsAt" type="datetime-local" required/></label><label>السعة<input name="capacity" type="number" min="1" max="30" defaultValue="1" required/></label><label>السعر<input name="price" type="number" min="0" defaultValue="0" required/></label>{onlineOnly&&<label>رابط اللقاء<input name="meetingUrl" type="url" required/></label>}{!onlineOnly&&<label>رابط اللقاء (للأونلاين)<input name="meetingUrl" type="url" /></label>}<button>حفظ الوقت</button></form><div className="schedule-slots">{slots.map(slot=><article key={slot.id}><small>{labels[slot.service_type]} · {slot.status}</small><h2>{slot.staff?.full_name||"الكوتش"}</h2><p>{new Date(slot.starts_at).toLocaleString("ar-SY")} — {new Date(slot.ends_at).toLocaleTimeString("ar-SY",{hour:"2-digit",minute:"2-digit"})}</p>{role==="admin"&&slot.status==="proposed"&&<div><button onClick={()=>review(slot.id,"approved")}>اعتماد</button><button className="reject" onClick={()=>review(slot.id,"rejected")}>رفض</button></div>}</article>)}</div></section></main>;
}
