"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

type Profile = { role: "admin" | "coach" | "investor" | "customer"; full_name: string; email: string };
const copy = {
  admin: { eyebrow: "بوابة الإدارة", title: "مركز التحكم بالنادي", lead: "أدر المستخدمين، النسب، والفواتير من نقطة واحدة.", cards: [["الرصيد المتاح", "2,850,000 ل.س"], ["طلبات تحتاج اعتماد", "4 عمليات"], ["تجديدات خلال 7 أيام", "7 متدربين"]], actions: ["إدارة المستخدمين", "ضبط نسب التوزيع", "مراجعة دفتر التدقيق"] },
  coach: { eyebrow: "بوابة الكوتش", title: "حسابك ومستحقاتك", lead: "تابع حصصك، متدربيك، ومستحقاتك المتاحة للسحب.", cards: [["المستحق من النادي", "200,000 ل.س"], ["سُحب هذا الشهر", "300,000 ل.س"], ["حصص هذا الأسبوع", "12 حصة"]], actions: ["عرض كشف الحساب", "متدربو اليوم", "طلب سحب مستحقات"] },
  investor: { eyebrow: "بوابة المستثمر", title: "شفافية مالية كاملة", lead: "اطلع على الدخل والمصروفات والتوزيع دون تعديل السجل.", cards: [["صافي ربح الشهر", "2,520,000 ل.س"], ["نسبتك الحالية", "50%"], ["توزيع بانتظار الاعتماد", "1,260,000 ل.س"]], actions: ["تقرير الأرباح", "حركة الأموال", "سجل التدقيق"] },
} as const;

export default function Portal() {
  const params = useParams<{ role: keyof typeof copy }>(); const router = useRouter(); const role = params.role in copy ? params.role : "coach"; const data = copy[role];
  const [profile, setProfile] = useState<Profile | null>(null); const [message, setMessage] = useState(""); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/auth/me").then(async r => ({ r, d: await r.json() })).then(({ r, d }) => { if (!r.ok || d.role !== role) return router.replace("/login"); setProfile(d); setLoading(false); }).catch(() => router.replace("/login")); }, [role, router]);
  async function createUser(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: f.get("name"), email: f.get("email"), password: f.get("password"), role: f.get("role") }) }); const result = await response.json(); setMessage(response.ok ? "تم إنشاء المستخدم وتفعيل بوابته بنجاح." : result.error); if (response.ok) { setShowForm(false); e.currentTarget.reset(); } }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/login"); }
  if (loading) return <main className="portal-loading" dir="rtl">جارِ فتح بوابتك الآمنة…</main>;
  return <main dir="rtl" className="portal-page"><header className="portal-top"><Link className="brand" href="/"><span className="brand-mark">ن</span>ناديك<span className="brand-dot">.</span></Link><div><span>{profile?.full_name}</span><button onClick={logout}>تسجيل الخروج</button></div></header><section className="portal-intro"><div><p className="eyebrow">{data.eyebrow}</p><h1>{data.title}</h1><p>{data.lead}</p></div>{role === "admin" && <button className="primary-button" onClick={() => setShowForm(true)}>＋ إنشاء مستخدم</button>}</section>{message && <p className="portal-message">{message}</p>}<section className="portal-stats">{data.cards.map(([label, value]) => <article key={label}><small>{label}</small><b>{value}</b><span>محدّث من دفتر النادي</span></article>)}</section><section className="portal-grid"><article className="portal-panel"><h2>اختصاراتك</h2><div className="portal-actions">{data.actions.map(action => <button key={action} onClick={() => setMessage(`تم فتح ${action}. ستظهر البيانات الحية فور إكمال ربط قاعدة البيانات.`)}>{action}<span>←</span></button>)}</div></article><article className="portal-panel"><h2>آخر تحديث</h2><div className="audit-list"><span><b>عملية موثقة</b><small>كل حركة تحمل وقتاً ومرجعاً ولا تُعدّل بصمت.</small></span><span><b>تنبيه ذكي</b><small>سيصلك إشعار عند تغير الرصيد أو قرب موعد الاستحقاق.</small></span><span><b>صلاحيات دقيقة</b><small>لا تظهر أي بيانات خارج دور حسابك.</small></span></div></article></section>{showForm && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setShowForm(false)}>×</button><form onSubmit={createUser}><p className="eyebrow">مستخدم جديد</p><h2>إنشاء بوابة مستقلة</h2><label>الاسم الكامل<input name="name" required /></label><label>البريد الإلكتروني<input name="email" type="email" required /></label><label>كلمة مرور مؤقتة<input name="password" type="password" minLength={10} required /></label><label>الدور<select name="role"><option value="coach">كوتش</option><option value="investor">مستثمر</option><option value="admin">إدارة</option><option value="customer">عميل / متدرب</option></select></label><button className="primary-button wide" type="submit">إنشاء الحساب وتفعيل الدور</button></form></section></div>}</main>;
}
