"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { money } from "@/app/_components/admin-shell";
type Role = "admin" | "coach" | "investor" | "customer";
type Profile = { role: Role; full_name: string; email: string; staffId?: string | null; memberId?: string | null };
const links: Record<Role, Array<[string,string]>> = {
  admin: [["إدارة المتدربين","/members"],["إدارة الكباتن","/coaches"],["إدارة الدورات","/dashboard/courses"],["المواعيد والحجوزات","/schedule"],["مواعيد الأونلاين","/schedule/online"],["الحسابات","/finance"],["المستخدمون","/users"]],
  coach: [["أوقاتي المتاحة","/schedule"],["جلسات الأونلاين","/schedule/online"],["دوراتي","/dashboard/courses"],["ملفي ومستحقاتي","/coaches"],["المتدربون المخصصون","/members"]],
  investor: [["التقرير المالي","/reports"],["الحركات المالية","/finance"]],
  customer: [["احجز موعداً","/book"],["التدريب الأونلاين","/online-learning"],["ملفي الرياضي","/members"],["المتجر","/shop"]],
};
export default function Portal(){const params=useParams<{role:Role}>();const router=useRouter();const[profile,setProfile]=useState<Profile|null>(null);const[summary,setSummary]=useState<{kpis:{monthlyIncome:number;monthlyExpenses:number;netProfit:number}}|null>(null);const[message,setMessage]=useState("");const[showForm,setShowForm]=useState(false);
useEffect(()=>{fetch("/api/auth/me").then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(!ok||data.role!==params.role){router.replace("/login");return;}setProfile(data);if(data.role==="admin"||data.role==="investor")fetch("/api/dashboard").then(response=>response.ok?response.json():null).then(setSummary);}).catch(()=>router.replace("/login"));},[params.role,router]);
async function createUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:form.get("name"),email:form.get("email"),password:form.get("password"),role:form.get("role")})});const data=await response.json();setMessage(response.ok?"تم إنشاء المستخدم وتفعيل حسابه.":data.error);if(response.ok)setShowForm(false)}async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login")}
if(!profile)return <main className="portal-loading" dir="rtl">جارٍ فتح بوابتك…</main>;const target=profile.role==="coach"&&profile.staffId?`/coaches/${profile.staffId}`:profile.role==="customer"&&profile.memberId?`/members/${profile.memberId}`:null;const cards=summary?[["دخل الشهر",money(summary.kpis.monthlyIncome)],["مصروفات الشهر",money(summary.kpis.monthlyExpenses)],["صافي الربح",money(summary.kpis.netProfit)]]:profile.role==="coach"?[["ملفك المالي","عرض المستحقات"],["مواعيدك","عرض الجدول"]]:profile.role==="customer"?[["ملفك الرياضي","اشتراكات وحضور"],["التدريب الأونلاين","دروسك المسجلة"]]:[["التقارير","وصول للقراءة فقط"]];
return <main dir="rtl" className="portal-page"><header className="portal-top"><Link className="brand" href="/"><span className="brand-mark">KO</span>KO Fighters<span className="brand-dot">.</span></Link><div><span>{profile.full_name}</span><button onClick={logout}>تسجيل الخروج</button></div></header><section className="portal-intro"><div><p className="eyebrow">بوابتك الخاصة</p><h1>{profile.role==="admin"?"مركز إدارة النادي":profile.role==="coach"?"حساب الكوتش":profile.role==="investor"?"بوابة المستثمر":"بوابة المتدرب"}</h1><p>تظهر لك البيانات المسموح بها فقط وفق دور حسابك.</p></div>{profile.role==="admin"&&<button className="primary-button" onClick={()=>setShowForm(true)}>＋ إنشاء مستخدم</button>}</section>{message&&<p className="portal-message">{message}</p>}<section className="portal-stats">{cards.map(([label,value])=><article key={label}><small>{label}</small><b>{value}</b><span>بيانات حية من النظام</span></article>)}</section><section className="portal-grid"><article className="portal-panel"><h2>اختصاراتك</h2><div className="portal-actions">{target&&<Link href={target}>ملفي التفصيلي <span>←</span></Link>}{links[profile.role].map(([label,href])=><Link key={href} href={href}>{label}<span>←</span></Link>)}</div></article><article className="portal-panel"><h2>الحماية والصلاحيات</h2><div className="audit-list"><span><b>وصول مقيّد</b><small>تُفحص الصلاحية في الخادم قبل تحميل البيانات.</small></span><span><b>سجل مالي موثّق</b><small>العمليات المالية لا تُعدّل من الواجهة مباشرة.</small></span></div></article></section>{showForm&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setShowForm(false)}>×</button><form onSubmit={createUser}><h2>إنشاء مستخدم</h2><label>الاسم<input name="name" required/></label><label>البريد<input name="email" type="email" required/></label><label>كلمة المرور<input name="password" type="password" minLength={10} required/></label><label>الدور<select name="role"><option value="coach">كوتش</option><option value="investor">مستثمر</option><option value="customer">متدرب</option><option value="admin">إدارة</option></select></label><button className="primary-button wide">إنشاء الحساب</button></form></section></div>}</main>}
