"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

type HomeData = { courses: Array<any>; products: Array<any>; coaches: Array<any>; achievements: Array<any>; settings: Record<string, string> };
const money = (value: number) => `${new Intl.NumberFormat("ar-SY").format(Number(value || 0))} ل.س`;

export default function KOHome() {
  const [data, setData] = useState<HomeData | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/public/home").then(async r => ({ ok: r.ok, data: await r.json() })).then(r => r.ok ? setData(r.data) : setError(r.data.error || "تعذر تحميل البيانات.")).catch(() => setError("تعذر الاتصال بقاعدة البيانات.")); }, []);
  return <main className="ko-site" dir="rtl">
    <header className="ko-nav"><Link href="/" className="ko-brand"><Image src="/ko-logo.png" alt="KO" width={48} height={48} priority /><span>KO<span>•</span></span></Link><nav><Link href="/about">من نحن</Link><Link href="/courses">الدورات</Link><Link href="/shop">المتجر</Link><Link href="/achievements">الإنجازات</Link><Link href="/contact">تواصل معنا</Link></nav><Link className="ko-login" href="/login">دخول النادي</Link></header>
    <section className="ko-hero"><div className="ko-hero-copy"><p className="ko-kicker">KO COMBAT CLUB · دمشق</p><h1>قوة منضبطة.<br /><em>مقاتل أقوى.</em></h1><p>بيئة تدريب احترافية للفنون القتالية، اللياقة، والقوة. كل حصة مصممة لتدفعك إلى المستوى التالي.</p><div className="ko-actions"><Link className="ko-btn primary" href="/courses">اشترك الآن</Link><Link className="ko-btn ghost" href="/shop">تسوّق المنتجات</Link></div><div className="ko-stats"><span><b>{data?.courses.length ?? "—"}</b> برامج تدريب</span><span><b>{data?.coaches.length ?? "—"}</b> كوتش محترف</span><span><b>KO</b> عقلية واحدة</span></div></div><div className="ko-hero-art"><Image src="/ko-logo.png" alt="هوية KO القتالية" fill priority sizes="(max-width: 800px) 92vw, 45vw" /></div></section>
    {error ? <section className="ko-alert">{error} — راجع إعداد قاعدة البيانات ثم أعد المحاولة.</section> : null}
    <section className="ko-section intro"><p className="ko-kicker">عن النادي</p><h2>التدريب هنا التزام، وليس مجرد وقت في الصالة.</h2><p>KO يجمع الانضباط القتالي مع التدريب الذكي والمتابعة الفردية. نبدأ من مستواك اليوم ونبني قوتك خطوة بخطوة.</p><Link href="/about">تعرّف على فلسفة KO ←</Link></section>
    <section className="ko-section"><div className="ko-section-head"><div><p className="ko-kicker">برامج KO</p><h2>اختر حصتك القادمة</h2></div><Link href="/courses">عرض جميع الدورات ←</Link></div><div className="ko-card-grid">{data ? data.courses.map(course => <article className="ko-course" key={course.id}><div className="ko-course-mark">{course.category || "KO"}</div><div><small>{course.level || "جميع المستويات"}</small><h3>{course.name}</h3><p>{course.short_description || course.schedule}</p><span>{course.staff?.full_name || "كوتش KO"} · {course.schedule}</span></div><footer><b>{money(course.monthly_price)}</b><Link href={`/courses/${course.id}`}>التفاصيل</Link></footer></article>) : <LoadingCards count={3} />}</div></section>
    <section className="ko-banner"><div><p className="ko-kicker">KO STORE</p><h2>تجهّز للتدريب مثل المحترفين.</h2><Link className="ko-btn cream" href="/shop">تصفح المتجر</Link></div><Image src="/ko-logo.png" alt="KO Store" width={270} height={270} /></section>
    <section className="ko-section"><div className="ko-section-head"><div><p className="ko-kicker">اختيارات المتجر</p><h2>منتجات متاحة الآن</h2></div><Link href="/shop">كل المنتجات ←</Link></div><div className="ko-product-grid">{data ? data.products.map(product => <Link className="ko-product" href={`/shop/${product.id}`} key={product.id}><div className="ko-product-image">{product.image_url ? <Image src={product.image_url} alt={product.name} fill sizes="260px" /> : <Image src="/ko-logo.png" alt="KO" fill sizes="260px" />}</div><small>{product.stock_quantity > 0 ? `متوفر · ${product.stock_quantity} قطعة` : "غير متوفر"}</small><h3>{product.name}</h3><b>{money(product.sale_price)}</b></Link>) : <LoadingCards count={4} />}</div></section>
    <section className="ko-section ko-coaches"><div className="ko-section-head"><div><p className="ko-kicker">فريق التدريب</p><h2>كوتش يدفعك للأمام</h2></div><Link href="/coaches">فريق الكوتش ←</Link></div><div className="ko-coach-grid">{data ? data.coaches.map(coach => <Link href={`/coaches/${coach.id}`} className="ko-coach" key={coach.id}><span>{coach.full_name?.slice(0, 1)}</span><div><h3>{coach.full_name}</h3><p>{coach.job_title}</p><small>{coach.specialties}</small></div></Link>) : <LoadingCards count={3} />}</div></section>
    <section className="ko-section"><div className="ko-section-head"><div><p className="ko-kicker">إنجازاتنا</p><h2>نقاتل لنتطور</h2></div><Link href="/achievements">كل الإنجازات ←</Link></div><div className="ko-achievements">{data?.achievements?.length ? data.achievements.map(item => <article key={item.id}><small>{new Date(item.achieved_at).toLocaleDateString("ar-SY")}</small><h3>{item.title}</h3><p>{item.athlete_name} · {item.competition}</p></article>) : <p className="ko-empty">ستظهر الإنجازات المنشورة هنا فور إضافتها من الإدارة.</p>}</div></section>
    <footer className="ko-footer"><div className="ko-brand"><Image src="/ko-logo.png" alt="KO" width={48} height={48}/><span>KO<span>•</span></span></div><p>قوة. انضباط. مجتمع.</p><div><Link href="/contact">تواصل معنا</Link><Link href="/login">بوابة النادي</Link></div></footer>
  </main>;
}
function LoadingCards({ count }: { count: number }) { return <>{Array.from({ length: count }).map((_, index) => <div className="ko-loading" key={index} />)}</>; }
