"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AdminShell, EmptyState, ErrorState, LoadingState, money, StatusBadge } from "@/app/_components/admin-shell";
import { WhatsAppAction } from "@/app/_components/whatsapp-action";

type Member = { id: string; member_code: string | null; full_name: string; phone: string | null; whatsapp: string | null; membership_status: string; renewal_date: string | null; monthly_fee: number; staff: { full_name: string } | null; subscription: { courses: { id: string; name: string; monthly_price: number } | null; end_date: string; amount: number } | null };

export default function MembersPage() {
  const [rows, setRows] = useState<Member[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [query, setQuery] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => { let cancelled = false; fetch(`/api/members?q=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}`).then(async response => ({ ok: response.ok, data: await response.json() })).then(({ ok, data }) => { if (cancelled) return; if (!ok) { setState("error"); return; } setRows(data.members); setState("ready"); }).catch(() => !cancelled && setState("error")); return () => { cancelled = true; }; }, [query, status]);
  const content = state === "loading" ? <LoadingState /> : state === "error" ? <ErrorState message="تعذر تحميل المتدربين. تحقق من صلاحية الإدارة واتصال Supabase." /> : rows.length === 0 ? <EmptyState title="لا يوجد متدربون" detail="أضف أول متدرب أو غيّر الفلاتر." /> : <article className="panel table-card"><div className="data-table"><table><thead><tr><th>المتدرب</th><th>الهاتف</th><th>واتساب سريع</th><th>الدورة الحالية</th><th>الكابتن</th><th>التجديد</th><th>الرسوم</th><th>الحالة</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><b>{row.full_name}</b><small>{row.member_code || "—"}</small></td><td>{row.phone || "—"}</td><td><WhatsAppAction phone={row.whatsapp || row.phone} name={row.full_name} /></td><td>{row.subscription?.courses ? <><b>{row.subscription.courses.name}</b><small>{money(row.subscription.amount)}</small></> : "لا يوجد اشتراك"}</td><td>{row.staff?.full_name || "غير مخصص"}</td><td>{row.renewal_date || "—"}</td><td>{money(row.monthly_fee)}</td><td><StatusBadge>{row.membership_status}</StatusBadge></td><td><Link href={`/members/${row.id}`}>عرض التفاصيل ←</Link></td></tr>)}</tbody></table></div></article>;
  return <AdminShell title="إدارة المتدربين" subtitle="ملفات حقيقية، اشتراكات، أرصدة، وحضور لكل متدرب." active="/members" action={<Link className="primary-button" href="/users">＋ إضافة مستخدم</Link>}><div className="data-toolbar"><input aria-label="بحث في المتدربين" value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث بالاسم أو الرقم أو الهاتف" /><select aria-label="فلترة الحالة" value={status} onChange={event => setStatus(event.target.value)}><option value="">كل الحالات</option><option>نشط</option><option>مبدئي</option><option>بانتظار الدفع</option><option>موقوف</option></select></div>{content}</AdminShell>;
}
