"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Slot = { id: string; service_type: string; starts_at: string; ends_at: string; capacity: number; price: number; available: number; staff?: { full_name?: string; job_title?: string } | null };
const types = [{ id: "private_training", label: "تدريب فردي" }, { id: "group_training", label: "تدريب مع مجموعة" }, { id: "consultation", label: "استشارة" }, { id: "online_training", label: "تدريب أونلاين" }] as const;
const labels: Record<string, string> = Object.fromEntries(types.map(type => [type.id, type.label]));
const money = (value: number) => `${new Intl.NumberFormat("ar-SY").format(Number(value || 0))} ل.س`;

export default function BookingPage() {
  const [slots, setSlots] = useState<Slot[]>([]); const [filter, setFilter] = useState(""); const [selected, setSelected] = useState<Slot | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`/api/booking/slots${filter ? `?serviceType=${filter}` : ""}`).then(async response => ({ ok: response.ok, data: await response.json() })).then(result => { if (!result.ok) setMessage(result.data.error || "تعذر تحميل المواعيد."); else setSlots(result.data.slots); }).catch(() => setMessage("تعذر الاتصال بالخادم.")).finally(() => setLoading(false)); }, [filter]);
  const grouped = useMemo(() => slots.reduce<Record<string, Slot[]>>((all, slot) => { const key = new Date(slot.starts_at).toLocaleDateString("ar-SY", { weekday: "long", month: "long", day: "numeric" }); (all[key] ??= []).push(slot); return all; }, {}), [slots]);
  async function reserve(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const partySize = Number(form.get("partySize") || 1); const guestNames = String(form.get("guestNames") || "").split("،").map(value => value.trim()).filter(Boolean); setMessage("جارٍ تأكيد الحجز…"); const response = await fetch("/api/booking", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ availabilityId: selected.id, partySize, guestNames, notes: form.get("notes") }) }); const data = await response.json(); if (!response.ok) { setMessage(response.status === 401 ? "سجّل الدخول كمتدرب أولاً لإتمام الحجز." : data.error || "تعذر الحجز."); return; } setMessage("تم تأكيد حجزك. ستجد الموعد في بوابتك الخاصة."); setSelected(null); setSlots(current => current.map(slot => slot.id === selected.id ? { ...slot, available: slot.available - partySize } : slot)); }
  return <main className="ko-site" dir="rtl"><header className="ko-nav"><Link href="/" className="ko-brand"><Image src="/ko-logo.png" alt="KO" width={48} height={48}/><span>KO<span>•</span></span></Link><nav><Link href="/courses">الدورات</Link><Link href="/book">الحجز</Link><Link href="/online-learning">التدريب الأونلاين</Link><Link href="/shop">المتجر</Link></nav><Link className="ko-login" href="/login">دخول النادي</Link></header><section className="booking-hero"><p className="ko-kicker">KO APPOINTMENTS</p><h1>احجز وقتك. <em>تدرّب بطريقتك.</em></h1><p>اختر جلسة فردية أو جماعية، تدريباً أونلاين، أو استشارة مع كوتش KO. لا يظهر هنا إلا الوقت المعتمد والمتاح.</p></section><section className="booking-content"><div className="booking-tabs">{[{ id: "", label: "كل الخدمات" }, ...types].map(type => <button key={type.id} className={filter === type.id ? "active" : ""} onClick={() => setFilter(type.id)}>{type.label}</button>)}</div>{message && <p className="booking-message">{message}</p>}{loading ? <p className="booking-empty">جارٍ تحميل الأوقات المتاحة…</p> : !slots.length ? <p className="booking-empty">لا توجد مواعيد متاحة في الوقت الحالي. ستظهر أوقات الكوتش فور اعتماد الإدارة لها.</p> : Object.entries(grouped).map(([day, daySlots]) => <section className="booking-day" key={day}><h2>{day}</h2><div className="booking-slot-grid">{daySlots.map(slot => <article className="booking-slot" key={slot.id}><small>{labels[slot.service_type]}</small><h3>{new Date(slot.starts_at).toLocaleTimeString("ar-SY", { hour: "2-digit", minute: "2-digit" })} — {new Date(slot.ends_at).toLocaleTimeString("ar-SY", { hour: "2-digit", minute: "2-digit" })}</h3><p>{slot.staff?.full_name || "كوتش KO"} · {slot.staff?.job_title || "مدرب محترف"}</p><div><b>{money(slot.price)}</b><span>{slot.available} مقاعد متبقية</span></div><button disabled={slot.available < 1} onClick={() => { setSelected(slot); setMessage(""); }}>{slot.available ? "احجز الموعد" : "اكتملت السعة"}</button></article>)}</div></section>)}</section>{selected && <div className="booking-modal"><form onSubmit={reserve}><button type="button" className="modal-close" onClick={() => setSelected(null)}>×</button><p className="ko-kicker">تأكيد الحجز</p><h2>{labels[selected.service_type]} مع {selected.staff?.full_name || "كوتش KO"}</h2><p>{new Date(selected.starts_at).toLocaleString("ar-SY")}</p><label>عدد الأشخاص<input name="partySize" type="number" min="1" max={Math.min(10, selected.available)} defaultValue="1" required /></label><label>أسماء المرافقين (اختياري، افصل بفاصلة عربية)<input name="guestNames" placeholder="أحمد، سارة" /></label><label>ملاحظة للكوتش (اختياري)<textarea name="notes" rows={3}/></label><button className="ko-btn red">تأكيد الحجز</button></form></div>}</main>;
}
