"use client";

import Link from "next/link";
import { useState } from "react";

const tabs = ["المعلومات", "الاشتراكات", "الدفعات والفواتير", "التطور والقياسات"] as const;
type Tab = typeof tabs[number];

export default function MemberProfilePage() {
  const [tab, setTab] = useState<Tab>("المعلومات");
  const [notice, setNotice] = useState("");
  return <main dir="rtl" className="member-profile-page"><header className="member-top"><Link href="/members">← العودة إلى المتدربين</Link><div><span className="avatar big mint">سم</span><div><p>ملف المتدرب</p><h1>سارة محمود</h1><small>عضوية نشطة · رقم #1028</small></div></div><button className="secondary-button" onClick={() => setNotice("تم فتح تعديل بيانات المتدربة.")}>تعديل البيانات</button></header>
    {notice && <div className="notice member-notice">✓ {notice}<button onClick={() => setNotice("")}>×</button></div>}
    <section className="member-profile-summary"><article><small>حالة الاشتراك</small><b className="green-text">نشط</b><span>ينتهي بعد يومين</span></article><article><small>الدورة الحالية</small><b>باقة اللياقة</b><span>3 حصص أسبوعيًا</span></article><article><small>الكابتن</small><b>فهد الأبطح</b><span>قوة وتحمل</span></article><article><small>الرصيد</small><b>٠ ل.س</b><span>لا توجد دفعات معلقة</span></article></section>
    <nav className="profile-tabs" aria-label="تفاصيل المتدرب">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <section className="profile-content">{tab === "المعلومات" && <InfoTab />}{tab === "الاشتراكات" && <SubscriptionsTab setNotice={setNotice} />}{tab === "الدفعات والفواتير" && <PaymentsTab setNotice={setNotice} />}{tab === "التطور والقياسات" && <ProgressTab setNotice={setNotice} />}</section>
  </main>;
}

function InfoTab() { return <div className="profile-grid"><article className="panel"><h2>البيانات الأساسية</h2><div className="info-lines"><span>رقم الهاتف <b>٠٩٣٣٠٠٠٠٠١</b></span><span>الواتساب <b>٠٩٣٣٠٠٠٠٠١</b></span><span>الجنس <b>أنثى</b></span><span>تاريخ الانضمام <b>01 يونيو 2026</b></span></div></article><article className="panel"><h2>ملاحظات الكابتن</h2><p className="profile-note">التركيز على اللياقة العامة وتقوية الجزء السفلي. الالتزام ممتاز خلال الأسبوعين الماضيين.</p><button className="secondary-button wide">إضافة ملاحظة</button></article><article className="panel full-panel"><h2>الجدول القادم</h2><div className="schedule-grid"><span><b>الأحد</b><small>06:00 م · قوة وتحمل</small></span><span><b>الثلاثاء</b><small>06:00 م · قوة وتحمل</small></span><span><b>الخميس</b><small>06:00 م · قوة وتحمل</small></span></div></article></div>; }
function SubscriptionsTab({ setNotice }: { setNotice: (text: string) => void }) { return <div className="profile-grid"><article className="panel full-panel"><div className="panel-heading"><div><h2>الاشتراك الحالي</h2><p>يمكن تجديده لمدد مختلفة مع توليد دفع وفاتورة تلقائيًا.</p></div><button className="primary-button" onClick={() => setNotice("تم إنشاء تجديد شهر واحد بقيمة ١٨٠٬٠٠٠ ل.س.")}>تجديد الاشتراك</button></div><div className="subscription-card"><div><span>باقة اللياقة الشهرية</span><b>180,000 ل.س</b><small>من 01 يوليو إلى 31 يوليو 2026</small></div><div className="subscription-status"><b>نشط</b><small>تبقى يومان</small></div></div></article><article className="panel"><h2>سجل الاشتراكات</h2><div className="mini-list"><span><b>يونيو 2026</b> باقة اللياقة <i>منتهٍ</i></span><span><b>مايو 2026</b> باقة اللياقة <i>منتهٍ</i></span></div></article><article className="panel"><h2>تنبيه التجديد</h2><p className="profile-note">يظهر تنبيه للمدير قبل انتهاء الاشتراك بـ 7 أيام، ويمكن إرسال رسالة واتساب جاهزة.</p><button className="secondary-button wide" onClick={() => setNotice("تم تجهيز رسالة واتساب للتجديد.")}>إرسال تذكير واتساب</button></article></div>; }
function PaymentsTab({ setNotice }: { setNotice: (text: string) => void }) { return <div className="profile-grid"><article className="panel full-panel"><div className="panel-heading"><div><h2>سجل الدفعات</h2><p>كل دفعة مرتبطة بالاشتراك والفاتورة.</p></div><button className="primary-button" onClick={() => setNotice("تم فتح نموذج تسجيل دفعة جديدة.")}>＋ تسجيل دفعة</button></div><div className="payment-list"><span><b>180,000 ل.س</b><small>تحويل · 01 يوليو 2026</small><i>فاتورة #4821</i><button onClick={() => setNotice("تم تجهيز الفاتورة للطباعة.")}>عرض الفاتورة</button></span><span><b>180,000 ل.س</b><small>نقدي · 01 يونيو 2026</small><i>فاتورة #4640</i><button onClick={() => setNotice("تم تجهيز الفاتورة للطباعة.")}>عرض الفاتورة</button></span></div></article><article className="panel"><h2>ملخص مالي</h2><div className="info-lines"><span>إجمالي المدفوع <b>360,000 ل.س</b></span><span>المتبقي <b className="green-text">0 ل.س</b></span></div></article></div>; }
function ProgressTab({ setNotice }: { setNotice: (text: string) => void }) { return <div className="profile-grid"><article className="panel"><div className="panel-heading"><div><h2>سجل التطور</h2><p>متابعة الوزن والملاحظات.</p></div><button className="text-button" onClick={() => setNotice("تم فتح تسجيل تطور جديد.")}>＋ إضافة سجل</button></div><div className="progress-log"><span><b>69.5 كغ</b><small>27 يوليو 2026 · التزام ممتاز</small></span><span><b>71.0 كغ</b><small>06 يوليو 2026 · بداية البرنامج</small></span></div></article><article className="panel"><div className="panel-heading"><div><h2>القياسات</h2><p>خصوصية للمتدربة والكابتن.</p></div><button className="text-button" onClick={() => setNotice("تم فتح نموذج القياسات.")}>＋ تسجيل قياس</button></div><div className="info-lines"><span>محيط الخصر <b>76 سم</b></span><span>محيط الورك <b>98 سم</b></span><span>نسبة الدهون <b>29٪</b></span></div></article><article className="panel full-panel"><h2>ملاحظة الكابتن التالية</h2><p className="profile-note">إعادة القياس بعد أسبوعين، ومراجعة تقدم تمارين السكوات واللانجز.</p></article></div>; }
